language: csharp
dist: focal
mono: none
dotnet: 6.0.202
env: SWIFT_VERSION=5.6.1
vm:
  size: large
jobs:
  - name: coverage
    install:
      - dotnet tool install -g dotnet-coverage
      - dotnet tool install -g dotnet-reportgenerator-globaltool
      - curl -Os https://uploader.codecov.io/latest/linux/codecov
      - chmod +x codecov
    script: PATH+=:$HOME/.dotnet/tools make coverage
