language: csharp
dist: focal
mono: none
dotnet: 6.0.300
jobs:
  - name: clang-regex
    install: sudo apt install clang-12
    script:
      - echo '#include <regex>' >hello.cpp
      - clang++-12 -std=c++20 -c -Wall -Werror hello.cpp
